apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: blue-green-demo
  namespace: default
spec:
  template:
    metadata:
      name: blue-green-demo-v1
    spec:
      containers:
        - image: gcr.io/knative-samples/knative-route-demo:blue
